import { avenirLt, elephantDisplay, geistMono, geistSans } from '@/styles/fonts/config';
import '@/styles/globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      className={`${avenirLt.className} ${elephantDisplay.variable} ${geistSans.variable} ${geistMono.variable} text-brand-primary h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">{children}</body>
    </html>
  );
}
